# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#config/redis.yml
master: 
  host: localhost 
  port: 6379 
slaves: 
    host: localhost 
    port: 6380 
#  - host: localhost 
#    port: 6381
